version: '2'

services:
    web-random:
        build: .
        ports:
            - "80:5000"
        depends_on:
            - mongo

    web-crud:
        build: .
        ports:
            - "81:5000"
        entrypoint: python ./flask-mongodb-example/crud.py
        depends_on:
            - mongo

    web-mqtt:
        build: .
        entrypoint: python ./flask-mongodb-example/mqtt.py
        depends_on:
            - mongo
            - mqtt
        tty: true

    web-fulltext-search:
        build: .
        ports:
            - "82:5000"
        entrypoint: python ./flask-mongodb-example/fulltext_search.py
        depends_on:
            - mongo

    mongo:
        image: mongo:3.4.0
        ports:
            - "27017:27017"

    mqtt:
        image: eclipse-mosquitto
        ports:
            - "1883:1883"